version: "3.9"
services:
  k6:
    image: loadimpact/k6
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./k6:/scripts

  influxdb:
    image: influxdb:1.8.10
    ports:
    - 8086:8086
    environment:
    - INFLUXDB_DB=telegraf
    - INFLUXDB_USER=telegraf
    - INFLUXDB_ADMIN_ENABLED=true
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=Welcome1
    volumes:
      - ./influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      # - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      # - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

    